# 1. Configuracion de la Base de Datos (Variables de Railway)
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configuracion de JPA / Hibernate
# 'update' creara las tablas automaticamente en Railway al arrancar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# 3. Configuracion del Servidor
# Railway asigna el puerto mediante la variable PORT
server.port=${PORT:8080}

# 4. Configuracion de Thymeleaf (Opcional pero recomendada)
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
